Repository Syknapse/Contribute-To-This-Project, pull requests merged in 2022-11, with the labels that each got.

#2044 kdipto1 card
  index.html
Labels: changes requested

#2047 Fix image paths in other language readme
  translations/README/ARABIC.md
  translations/README/BANGLA.md
  translations/README/FRENCH.md
  translations/README/German.md
  translations/README/ITALIAN.md
  translations/README/POLISH.md
  translations/README/PORTUGUESE.md
  translations/README/SERBIAN.md
  translations/README/SPANISH.md
  translations/README/TURKISH.md
Labels: enhancement

#2041 Fix fork image path in korean readme
  translations/README/KOREAN.md
Labels: enhancement

#1936 cleaned some code
  assets/style.css
Labels: enhancement

#2039 Add translate for maintainer_guide in japanese
  translations/maintainer_guide/maintainer_guide_japanese.md
  translations/translation.md
Labels: enhancement

#2043 Add translate for README in japanese
  README.md
  translations/README/JAPANESE.md
  translations/translation.md
Labels: enhancement

#2055 Neobit's card
  index.html
Labels: changes requested

#2056 added new card and fixes the card
  assets/style.css
  index.html
Labels: changes requested

#2063 amyyalex's card
  index.html
Labels: changes requested

#2062 Added lertsoft information card
  index.html
Labels: changes requested

#2060 Meshack
  assets/style.css
  index.html
Labels: changes requested

#2076 arash arora's card
  index.html
Labels: changes requested

#2078 Improved Hero-Section UI
  assets/style.css
  index.html
Labels: enhancement, good first issue

#2077 removing JQuery from the project
  assets/script.js
  prettier.config.js
Labels: enhancement

#2086 Olubimi Michael added a new card
  index.html
Labels: changes requested

#2089 Changed the style of project SEARCHBAR
  assets/style.css
Labels: enhancement

#2105 first pr
  readme-only/fork.png
Labels: enhancement

#2108 gushiwen's card
  index.html
Labels: changes requested

#2107 added card for khageshor giri in index.html file
  index.html
Labels: changes requested

#2106 ScrollToTop Btn UI Improved
  assets/script.js
  assets/style.css
  index.html
Labels: enhancement, awaiting-response

#2094 Fixed dark view toggle and search bar when focused
  assets/script.js
  assets/style.css
Labels: enhancement, good first issue

#2117 Syncere's Card
  index.html
Labels: changes requested

#2120 Added Smooth ScrollToTop Functionality
  assets/style.css
Labels: enhancement, changes requested, awaiting-response
