Repository Syknapse/Contribute-To-This-Project, pull requests merged in 2022-10, with the labels that each got.

#1735 Junaid's Card Added
  index.html
Labels: hacktoberfest-accepted

#1736 add muanra's card
  index.html
Labels: hacktoberfest-accepted

#1713 Added my card.
  index.html
Labels: hacktoberfest-accepted

#1738 Update index.html
  index.html
Labels: hacktoberfest-accepted

#1734 BhawanaSankhla's card
  index.html
Labels: hacktoberfest-accepted

#1739 Dark's Card
  index.html
Labels: hacktoberfest-accepted

#1741 update index.html
  index.html
Labels: hacktoberfest-accepted

#1742 Vikash's card
  index.html
Labels: hacktoberfest-accepted

#1743 Add Mir Sahil card info
  index.html
Labels: hacktoberfest-accepted

#1721 Added MEaly-icepts card
  index.html
Labels: changes requested

#1729 Update index.html with Emmanuel's card
  index.html
Labels: changes requested

#1725 Add my card information
  index.html
Labels: changes requested

#1748 lauti's card is ready
  index.html
Labels: hacktoberfest-accepted

#1761 Added supratim card details
  index.html
Labels: hacktoberfest-accepted

#1765 Advie's card
  index.html
Labels: hacktoberfest-accepted

#1766 added avinash-Card
  index.html
  terminal-tutorial.md
Labels: hacktoberfest-accepted

#1768 Add hosam card info
  index.html
Labels: hacktoberfest-accepted

#1769 Madhavi's card added
  index.html
Labels: hacktoberfest-accepted

#1770 Aman Chopra Card
  index.html
Labels: hacktoberfest-accepted

#1771 Tasneem's card
  index.html
Labels: hacktoberfest-accepted

#1772 Added nidhi-card
  index.html
Labels: hacktoberfest-accepted

#1774 Add Estitxu Larralde's card info
  index.html
Labels: hacktoberfest-accepted

#1693 Added my card to project
  index.html
Labels: changes requested

#1755 Add my card information
  index.html
Labels: hacktoberfest-accepted

#1776 Updated index.html
  index.html
Labels: changes requested

#1778 Add Hitarth Srivastava card info
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1784 tkniki card info
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1782 Add Mcube Card Info
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1781 Added Card "Cade Humphreys"
  .history/index_20221002110255.html
  .history/index_20221002111534.html
  .history/index_20221002111739.html
  .history/index_20221002111857.html
  index.html
Labels: hacktoberfest-accepted

#1783 add name card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, changes requested

#1793 Aditya's card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1785 added Ronen Hammond card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, changes requested

#1795 Add my jimit-card information
  index.html
Labels: hacktoberfest-accepted

#1794 abel's card
  index.html
Labels: hacktoberfest-accepted

#1791 Add GilangKharisma card info
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1775 Update index.html
  index.html
Labels: hacktoberfest-accepted

#1787 Yifan's card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1788 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1799 Pranavv's card
  index.html
Labels: hacktoberfest-accepted

#1801 MarcoSchiavello's card
  index.html
Labels: hacktoberfest-accepted

#1802 Alisha's card
  index.html
Labels: hacktoberfest-accepted

#1798 index.html update by mohit for hacktober
  index.html
Labels: hacktoberfest-accepted

#1805 Makendran's Card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1803 Add my card information
  index.html
Labels: hacktoberfest-accepted

#1806 Update index.html
  index.html
Labels: hacktoberfest-accepted, changes requested

#1812 Add Ravitej card info
  index.html
Labels: hacktoberfest-accepted

#1815 Bijay Dulal Card
  index.html
Labels: hacktoberfest-accepted

#1816 Pharis Njuguna Card
  index.html
Labels: hacktoberfest-accepted

#1818 adds Aum Pandya contribution
  index.html
Labels: hacktoberfest-accepted

#1821 Add azhar luthfi card info
  index.html
Labels: hacktoberfest-accepted

#1813 Added Sushant Gangwar Card Info
  index.html
Labels: changes requested

#1790 Update index.html
  index.html
Labels: changes requested

#1807 Added new card named Hina.
  index.html
Labels: changes requested

#1820 Added card of my name
  index.html
Labels: hacktoberfest-accepted

#1825 Added Yasaswini Ganji Card on index.html
  index.html
Labels: hacktoberfest-accepted

#1823 banjobyster's card add
  index.html
Labels: hacktoberfest-accepted

#1827 Thanks for letting me in. :)
  index.html
Labels: hacktoberfest-accepted

#1828 feat: add new card
  index.html
Labels: hacktoberfest-accepted

#1829 Vaishnao Wankar's Card
  index.html
Labels: hacktoberfest-accepted

#1830 My details added
  index.html
Labels: hacktoberfest-accepted

#1833 Add fariq-card card info
  index.html
Labels: hacktoberfest-accepted

#1834 siddak's card
  index.html
Labels: hacktoberfest-accepted

#1836 updated my data using #code branch
  index.html
Labels: hacktoberfest-accepted

#1837 Abdulkerim a card
  index.html
Labels: hacktoberfest-accepted

#1841 Update index.html
  index.html
Labels: hacktoberfest-accepted

#1846 Sirin Koca card update
  index.html
Labels: hacktoberfest-accepted

#1847 Add CaCl2's Card
  index.html
Labels: hacktoberfest-accepted

#1849 Added a new card
  index.html
Labels: hacktoberfest-accepted

#1843 Update index.html
  index.html
Labels: hacktoberfest-accepted, changes requested

#1850 I've added my(atanu3000) card.
  index.html
Labels: hacktoberfest-accepted

#1853 IceMaur card
  index.html
Labels: hacktoberfest-accepted

#1859 Info card added - Altaf
  index.html
Labels: hacktoberfest-accepted

#1856 Contributed towards Hacktoberfest
  index.html
Labels: hacktoberfest-accepted

#1851 Update index.html
  index.html
Labels: hacktoberfest-accepted

#1857 updated index.html
  index.html
Labels: hacktoberfest-accepted

#1861 Add Sheldonholic card info
  index.html
Labels: hacktoberfest-accepted

#1863 Richard card
  index.html
Labels: hacktoberfest-accepted

#1866 iabhaychandel's card
  index.html
Labels: hacktoberfest-accepted

#1840 ialexanderbrito's card
  index.html
Labels: changes requested

#1845 Amad3eu's card
  index.html
Labels: changes requested

#1867 Update index.html
  index.html
Labels: hacktoberfest-accepted

#1855 I've added my(shubham yadav) card.
  index.html
Labels: hacktoberfest-accepted

#1874 Ayaan's card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1875 Add pranav card info
  index.html
Labels: hacktoberfest-accepted

#1876 added Name card in index.html
  index.html
Labels: hacktoberfest-accepted

#1879 Update index.html
  index.html
Labels: hacktoberfest-accepted

#1844 Biljana kotevska's card
  index.html
Labels: changes requested

#1882 Tarun's card
  assets/style.css
  index.html
Labels: hacktoberfest-accepted

#1883 Adding jatin's card
  index.html
Labels: hacktoberfest-accepted

#1884 Shreejan-35's card
  index.html
Labels: hacktoberfest-accepted

#1885 Update index.html
  index.html
Labels: hacktoberfest-accepted

#1888 ADDED MY CARD IN HTML
  index.html
Labels: hacktoberfest-accepted

#1890 Fixed fork.PNG broken link
  README.md
Labels: hacktoberfest-accepted

#1894 Add Saroj's Card Information
  index.html
Labels: hacktoberfest-accepted

#1895 Jayasri-210 card info
  index.html
Labels: hacktoberfest-accepted

#1896 Edit index.html
  index.html
Labels: hacktoberfest-accepted

#1897 Aditya Kumar Sahu's card
  index.html
Labels: hacktoberfest-accepted

#1889 Adding Arvindh's card information
  index.html
Labels: hacktoberfest-accepted

#1869 Add french missing translation
  translations/README/FRENCH.md
Labels: enhancement, hacktoberfest-accepted

#1891 fixed longs text issue in cards
  assets/style.css
Labels: enhancement, hacktoberfest-accepted

#1893 Fixed prettier for html
  README.md
  index.html
Labels: enhancement, hacktoberfest-accepted

#1900 Vaibhav's Card Added
  index.html
Labels: hacktoberfest-accepted

#1901 Maria Theresa Contributor card
  index.html
Labels: hacktoberfest-accepted

#1904 feat: added border radius to search bar
  assets/style.css
  index.html
  translations/README/FRENCH.md
Labels: enhancement

#1920 requested changes are made
  index.html
Labels: changes requested

#1915 added card of raj Mhatre
  index.html
Labels: changes requested

#1930 Princess's card
  index.html
Labels: changes requested

#1944 Update index.html
  index.html
Labels: changes requested

#1953 Oluwatimilehin Esan's Card
  index.html
Labels: changes requested

#1956 Added Mariia's card
  index.html
Labels: changes requested

#1973 Add my card information
  index.html
Labels: changes requested

#1995 add stefaan card info
  index.html
Labels: changes requested

#2009 Add rRubedog Card
  index.html
Labels: changes requested

#2021 add my card
  index.html
Labels: changes requested

#2023 Jeevan's card
  index.html
Labels: changes requested
