Repository Syknapse/Contribute-To-This-Project, pull requests merged in 2023-10, with the labels that each got.

#2986 Added My name
  index.html
Labels: changes requested

#3034 Jacob Summers' card
  index.html
Labels: changes requested

#2958 Updated existing README/KOREAN.md file. #2826
  translations/README/KOREAN.md
Labels: enhancement

#3146 css styling updates
  assets/style.css
  index.html
Labels: changes requested

#3203 Subhayu's Card
  index.html
Labels: changes requested

#3184 New italian translation!
  translations/README/ITALIAN.md
Labels: enhancement, translation

#3250 Update HINDI.md
  translations/README/HINDI.md
Labels: enhancement

#3259 Updated the index.html with my information
  index.html
Labels: changes requested

#3152 on hover backtotop button animates
  assets/style.css
Labels: enhancement, changes requested

#2968 Add terminal_tutorial.ger.md #2898
  terminal_tutorial.md
  translations/README.md
  translations/terminal_tutorial/terminal_tutorial.ger.md
Labels: enhancement, changes requested

#3264 Create maintainer_guide.mar.md
  translations/maintainer_guide/maintainer_guide.mar.md
Labels: changes requested

#3280 Added Translation for maintainer's guide in Russian
  translations/README.md
  translations/maintainer_guide/maintainer_guide.rus.md
Labels: changes requested

#3285 Update maintainer_guide.mar.md
  translations/maintainer_guide/maintainer_guide.mar.md
Labels: enhancement

#3243 Create ci for auto close pr, issues
  .github/workflows/stale.yml
Labels: enhancement

#3293 Added Parth Dwivedi card information
  index.html
Labels: changes requested

#3245 Added Saurabh Chaudhry card info
  index.html
Labels: changes requested, Stale

#3319 README.md: fixed other language table
  README.md
Labels: enhancement

#3258 Create maintainer_guide.fre.md
  translations/maintainer_guide/maintainer_guide.fra.md
Labels: enhancement, changes requested, Stale

#3311 [ADDED]: Killer2OP's Card
  index.html
Labels: changes requested

#3329 Kuba card
  .idea/workspace.xml
  index.html
Labels: changes requested, intentions not clear
