Repository Syknapse/Contribute-To-This-Project, pull requests merged in 2023-09, with the labels that each got.

#2898 Add terminal tutorial pt br.md
  terminal_tutorial.md
  translations/terminal_tutorial/terminal_tutorial.pt-br.md
  translations/translation.md
Labels: changes requested

#2908 Add AuburnMedia card
  index.html
Labels: changes requested

#2924 Add the Traditional Chinese translation to the German maintainer guide
  translations/maintainer_guide/maintainer_guide.ger.md
Labels: awaiting-response

#2934 Created maintainer_guide.hin.md
  translations/maintainer_guide/maintainer_guide.hin.md
Labels: enhancement, translation

#2919 Changed the Translation Hindi README file
  translations/README/HINDI.md
Labels: enhancement, translation, awaiting-response

#2932 Add bhavuk2002 card info
  index.html
Labels: changes requested

#2928 Create file for Swahili translation
  translations/README/SWAHILI.md
Labels: enhancement, translation

#2943 Brynjar H's card
  index.html
Labels: changes requested

#2954 add Plutobby
  index.html
Labels: changes requested

#2966 sreshta
  index.html
Labels: changes requested
