Repository Syknapse/Contribute-To-This-Project, pull requests merged in 2023-02, with the labels that each got.

#2335 Update index.html
  index.html
Labels: changes requested

#2289 Fix #2234
  assets/script.js
  index.html
Labels: enhancement, good first issue, awaiting-response

#2330 Added card of Dhruvin #2329
  README.md
  index.html
  translations/README/HINDI.md
Labels: enhancement

#2346 prashant commit
  index.html
Labels: changes requested

#2357 Add my card information
  index.html
Labels: changes requested

#2360 Stelios Achtaridis's card
  index.html
Labels: changes requested

#2363 Copy template card
  index.html
Labels: changes requested

#2375 Updated index.html pushed to test branch
  index.html
Labels: changes requested
