Repository Syknapse/Contribute-To-This-Project, pull requests merged in 2024-04, with the labels that each got.

#3655 mentioned user_handle in index.html
  index.html
Labels: enhancement

#3717 Winkel's Card
  index.html
Labels: changes requested, Stale

#3726 Deadly-Carp's card
  index.html
Labels: changes requested

#3659 Daniel Lounsbury
  index.html
Labels: changes requested, Stale

#3668 Leu1 card
  index.html
Labels: changes requested, Stale

#3671 Jen's card
  index.html
Labels: changes requested, Stale

#3674 Angel's USERNAME-card
  index.html
Labels: changes requested, Stale

#3701 My first first contribution @lds.uk00
  index.html
Labels: changes requested, Stale

#3718 Update index.html
  index.html
Labels: changes requested, Stale

#3691 included *Your_Name* in the TEMPLATE Comments for ease
  index.html
Labels: enhancement
