Repository Syknapse/Contribute-To-This-Project, pull requests merged in 2024-01, with the labels that each got.

#3494 AJ Sappenfield's Contribution
  index.html
Labels: changes requested

#3492 Adam Magyar's card
  index.html
Labels: changes requested

#3506 SWAHILI.md file Translation.
  translations/README/SWAHILI.md
Labels: enhancement, good first issue, translation

#3490 Manideep's card
  index.html
Labels: changes requested, Stale

#3516 macmatthew's card
  index.html
Labels: changes requested

#3508 Chard's Card
  index.html
Labels: changes requested, Stale

#3510 Updated German README-File
  translations/README/GERMAN.md
Labels: changes requested, Stale

#3512 Dutch translation of ReadMe file
  README.md
  translations/README.md
  translations/README/DUTCH.md
Labels: good first issue, translation, changes requested

#3521 Update index.html
  index.html
Labels: changes requested

#3519 andrespulido-card
  index.html
Labels: changes requested

#3522 rootofpi card
  index.html
Labels: changes requested
